services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: assessment-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Passw0rd!12345"
    ports:
      - "14333:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Passw0rd!12345' -Q 'SELECT 1' -C || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20

  api:
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    container_name: assessment-api
    depends_on:
      sql:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=sql;Database=AssessmentDb;User Id=sa;Password=Passw0rd!12345;TrustServerCertificate=True;"
    ports:
      - "5247:8080"

  web:
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    container_name: assessment-web
    depends_on:
      - api
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      Api__BaseUrl: "http://api:8080"
    ports:
      - "5158:8080"
